### ISSUE TITLE
DB

### ISSUE THREAD

**Issue by eDigirolamo** [waffer102/thanksfromme#1]
Trying to set this up & I created a db using the info from USER.php but it is not allowing me to login. Also what is your db setup like? Thanks

And yes I set values correctly for my db in config.php

**Comment by waffer102** [comment]
Hi Edward, the database setup is kind of messy right now. I will try to
export my sample database structure tonight and send it over to you.

**Comment by waffer102** [comment]
I uploaded a demo database you should be able to use to get your project up and running.
