### ISSUE TITLE
Intranet site

### ISSUE THREAD

**Issue by Drexman8244** [waffer102/thanksfromme#2]
Hello again, 
I am trying to use this on a local webserver that I use for intranet not a typical website. I have been having trouble and then I realized your index.php and login.php have Location set you your https://northstar.thanksfrom.me/login.php and points me to your site. 

When I change this in both index.php from your site to login.php and login.php to my to my local directory nothing happens and the page is blank.

**Comment by waffer102** [comment]
That top line of code is checking to see if it is HTTPS and then redirecting if not.  This could be causing issues on your local setup. You can remove that code and see if it fixes things.

**Comment by Drexman8244** [comment]
Thanks for the reply I decided to move on to adding it to a webserver instead but now I am having major issues with the file paths and not being able to find the css and js files in the correct path. The page loads plain text and logs me in. But I still get these errors when I set everything up in the initialize.php

![screen shot 2018-01-09 at 3 28 02 pm](https://user-images.githubusercontent.com/3252734/34741770-c44d255c-f551-11e7-943a-590908a4f9a5.png)

**Comment by waffer102** [comment]
My best guess is this has something to do with the setup of your webserver. If you find the proper URL for the css and js files and then adjust the header.php file within the layouts folder accordingly it should do the trick.
