### ISSUE TITLE
Profile Image Upload

### ISSUE THREAD

**Issue by eDigirolamo** [waffer102/thanksfromme#3]
hello,

having lots of trouble trying to figure out why this wont allow me to upload files. 
I have set the directory for pictures to 777 but still nothing.

**Comment by waffer102** [comment]
Are you getting an error message? Is your directory structure setup properly? Is your server configured to accept uploads?

**Comment by waffer102** [comment]
I haven't heard anything for a while, I will assume you got it figured out.
